# docker-compose.yml
version: "3.8"

services:
  api:
    container_name: hotels-rag-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENABLE_LLM=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=gpt-4o-mini
      - SKIP_LOAD_ON_START=0
    expose:
      - "8000"
    restart: unless-stopped

  web:
    container_name: hotels-rag-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
