# docker-compose.yml
version: "3.8"

services:
  api:
    container_name: hotels-rag-api
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    restart: unless-stopped

  web:
    container_name: hotels-rag-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
