version: "3.8"

services:
  api:
    container_name: hotels-rag-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    container_name: hotels-rag-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    restart: unless-stopped

