# docker-compose.yml
version: "3.8"

services:
  api:
    container_name: hotels-rag-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENABLE_LLM=1
      - OPENAI_API_KEY=${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}
      - LLM_MODEL=gpt-4o-mini
      - SKIP_LOAD_ON_START=0
    expose:
      - "8000"
    restart: unless-stopped

  web:
    container_name: hotels-rag-web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
